# Generated by Django 3.0.4 on 2020-04-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='ststus',
            field=models.IntegerField(default=0),
        ),
    ]
