# Generated by Django 3.0.4 on 2020-04-22 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0002_clients_ststus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='ststus',
            new_name='status',
        ),
    ]
